import {Dimensions, StyleSheet} from 'react-native';
export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 15,
  FONT_SIZE_LARGE: 18,
  FONT_SIZE_BUTTON: 20,
  FONT_SIZE_HIGH: 30,
  PRIMARY_COLOR: '#5C6EF8',
  SECONDARY_COLOR: '#6471E5',
  BACKGROUND_COLOR_LIGHT: '#F7F7F7',
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '600',
  FONT_WEIGHT_BLOD: '700',
  FONT_WEIGHT_HEAVY: '800',
  CONTAINER_WIDTH: Dimensions.get('screen').width - 20,
};
